version: "3"
services:
  react-app:
    image: tanmaydas438/covidcare-client:latest
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      mern-app:
        ipv4_address: 172.20.0.10
  api-server:
    image: tanmaydas438/covidcare-server:latest
    ports:
      - "3001:3001"
    networks:
      mern-app:
        ipv4_address: 172.20.0.11
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.23-xenial
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
# networks:
#   mern-app:
#     name: mern-app
#     driver: bridge
networks:
  mern-app:
    driver: bridge
    name: mern-app
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  mongo-data:
    driver: local
